### ISSUE TITLE
DocsAPI is not defined

### ISSUE THREAD

**Issue by zopyx** [ONLYOFFICE/onlyoffice-plone#4]
I am getting this JS error when click on the ONLYOFFICE EDIT action (Plone 5.2, Python 3)

<img width="1295" alt="Bildschirmfoto 2020-04-13 um 13 53 55" src="https://user-images.githubusercontent.com/594239/79118469-51d59000-7d8e-11ea-9119-465187701337.png">

**Comment by alexanderonlyoffice** [comment]
@zopyx, it seems that the Document Server is not connected to your Plone instance. Please follow this [link](https://github.com/ONLYOFFICE/onlyoffice-plone#configuring-plone-onlyoffice-integration-plugin) to find an installation guide on how to integrate ONLYOFFICE Document Server with Plone.

Please send me also the screenshot of the page with the integration app settings.

**Comment by zopyx** [comment]
This should be added to the onlyoffice.connector README on PyPI.

**Comment by alexanderonlyoffice** [comment]
@zopyx, please note that the guide you mentioned is a copy of our guide from GitHub and there is information about the need to have ONLYOFFICE open source or Integration Edition Document Server deployed on the server. 

From the 'Installing ONLYOFFICE Document Server' section:

> You will need an instance of ONLYOFFICE Document Server that is resolvable and connectable both from Plone and any end-clients.

**Comment by zopyx** [comment]
Sorry for being bitchy but as user of Plone:
- I installed the add-on in Plone
- I configured the add-in Plone by adding the URL of my OnlyOffice instance to the configuration panel inside Plone
- I uploaded file and clicked on "Edit in Onlyoffice"...
If there is an error or a configuration, it should be handled and reported properly on the UI level instead of throwing an exception that is only visible on the browser console.

**Comment by alexanderonlyoffice** [comment]
@zopyx, please specify what behavior of the editor you encounter when clicking on the 'Edit' button. 

Please specify if you have a dedicated ONLYOFFICE Document Server on another machine.

> I configured the add-in Plone by adding the URL of my OnlyOffice instance to the configuration panel inside Plone

Please open the Document Server web page in browser and send me the screenshot of the page you see.

**Comment by zopyx** [comment]
I revisited this issue with a fresh checkout from `deploy` branch against https://plonetrial.onlyoffice.eu

Same issue...

Problem is this:

```
 GET https://plonetrial.onlyoffice.eu//web-apps/apps/api/documents/api.js net::ERR_ABORTED 404 (Not Found)
onlyoffice-edit?_authenticator=36129482830767339f6b40e107a59c445f233f97:451 Uncaught ReferenceError: DocsAPI is not defined
    at onlyoffice-edit?_authenticator=36129482830767339f6b40e107a59c445f233f97:451 
```

**Comment by alexanderonlyoffice** [comment]
@zopyx, please note that you are trying to integrate Plone with the ONLYOFFICE Cloud Solution. Document Editor of the Cloud Solution cannot be integrated with any of third-party applications, as it is another type of the product. You have to deploy the Integration Edition Document Server or free open source version on your own server or on one provided by any hosting service. 

Please follow this link to find the installation guides of the Integration Edition Document Server: https://helpcenter.onlyoffice.com/server/integration-edition/index.aspx
These guides are for the open source version: https://helpcenter.onlyoffice.com/server/document.aspx

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
